<?php

namespace PM\SurveythorBundle\Repository\SurveyItems;

use PM\SurveythorBundle\Repository\BaseRepository;

/**
 * ItemGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemGroupRepository extends BaseRepository
{
}
