AppBundle\Entity\AllowedOrigin:
    type: entity
    table: allowed_origin
    gedmo:
        loggable:
            loggable: true
    id:
        id:
            type: uuid
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        title:
            type: string
        originName:
            type: string
        description:
            type: text
            nullable: true
        isActive:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdBy:
            type: string
            gedmo:
                blameable:
                    on: create
            nullable: true
        updatedBy:
            type: string
            gedmo:
                blameable:
                    on: update
            nullable: true
