AppBundle\Entity\ResultItems\ResultTextItem:
    type: entity
    table: result_text_item
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToOne:
        resultItem:
            targetEntity: AppBundle\Entity\ResultItem
            inversedBy: resultTextItem

    fields:
        text:
            type: text

    lifecycleCallbacks: {  }
