<?php

namespace PM\SurveythorBundle\Repository\ResultItems;

/**
 * ResultTextItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultTextItemRepository extends \Doctrine\ORM\EntityRepository
{
}
