imports:
    - { resource: config.yml }

parameters:
  twig.param.surveythor_host: 'http://surveythor-demo-frontend-app.herokuapp.com' # dirty workaround atm; we will need to set it via env vars later like %env(JAWSDB_URL)% e.g.

doctrine:
    dbal:
        url: "%env(JAWSDB_URL)%"
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type: console
