
embed_survey_edit:
    path: /edit/{survey}
    defaults: { _controller: app.controller.embed_controller:editSurveyAction }


embed_survey_execute:
    path: /result/{survey}
    defaults: { _controller: app.controller.embed_controller:executeSurveyAction }


embed_survey_evaluate:
    path: /evaluate/{survey}
    defaults: { _controller: app.controller.embed_controller:evaluateSurveyAction }
