bunny_result_evaluation:
    path: /bunny/{result}
    defaults: { _controller: app.controller.bunny_evaluation_controller:evaluateResultAction }

custom_result_evaluation:
    path: /custom/{result}
    defaults: { _controller: app.controller.custom_evaluation_controller:evaluateResultAction }
