result_new:
    path: /new/{survey}/{embedFrame}
    defaults: { _controller: app.controller.result_controller:newAction, embedFrame: null}
result_next:
    path: /next/{result}/{resultItem}
    defaults: { _controller: app.controller.result_controller:nextAction }
result_prev:
    path: /prev/{result}/{resultItem}
    defaults: { _controller: app.controller.result_controller:prevAction }
result_first:
    path: /first/{survey}
    defaults: { _controller: app.controller.result_controller:firstAction }
result_last:
    path: /last/{result}/{resultItem}
    defaults: { _controller: app.controller.result_controller:lastAction }
