survey_index:
    path: /
    defaults: { _controller: app.controller.survey_controller:indexAction }

survey_new:
    path: /new
    defaults: { _controller: app.controller.survey_controller:newAction }

survey_edit:
    path: /edit/{survey}
    defaults: { _controller: app.controller.survey_controller:editAction }

survey_update_title:
    path: /update-title/{survey}
    defaults: { _controller: app.controller.survey_controller:updateTitleAction }

survey_update_result_evaluation_route_name:
    path: /update-result-evaluation-route-name/{survey}
    defaults: { _controller: app.controller.survey_controller:updateResultEvaluationRouteNameAction }

survey_evaluations_last:
    path: /evaluations/last
    defaults: { _controller: app.controller.survey_controller:evaluationsLastAction }

survey_evaluations:
    path: /evaluations/{survey}
    defaults: { _controller: app.controller.survey_controller:evaluationsAction }
