services:
    _defaults:
        autowire: true

    AppBundle\Repository\AllowedOriginRepository: ~

    AppBundle\Repository\ChoiceRepository: ~

    AppBundle\Repository\ConditionRepository: ~

    AppBundle\Repository\ResultRepository: ~

    AppBundle\Repository\SurveyItemRepository: ~

    AppBundle\Repository\SurveyRepository: ~
