imports:
    - { resource: services_controller.yml }
    - { resource: services_repository.yml }

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.authorization_checker"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    app.event_listener.response_header_listener:
        class:     AppBundle\EventListener\ResponseHeaderListener
        autowire:  true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 1 }

    app.event_subscriber.custom_result_ready_subscriber:
            class: AppBundle\Event\CustomResultReadySubscriber
            autowire: true
            tags:
                - { name: kernel.event_listener, event: result.ready, method: onResultReady }

    easycorp.easylog.handler:
        class: EasyCorp\EasyLog\EasyLogHandler
        public: false
        arguments:
            - '%kernel.logs_dir%/%kernel.environment%.log'

    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
