<?php

namespace PM\SurveythorBundle\Repository;

use PM\SurveythorBundle\Entity\Condition;
use PM\SurveythorBundle\Entity\SurveyItems\Question;
use PM\SurveythorBundle\Entity\Choice;

/**
 * ConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionRepository extends BaseRepository
{
    /**
     * @param Question $question
     *
     * @return Condition[]
     */
    public function getConditionsByQuestion(Question $question)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->select('c')
            ->join('c.choices', 'ch')
            ->where('ch.question = :idQuestion')
            ->setParameter('idQuestion', $question->getId());

        return $qb->getQuery()->getResult();
    }

    /**
     * @param Choice $choice
     *
     * @return Condition[]
     */
    public function getConditionsByChoice(Choice $choice)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->select('c')
            ->join('c.choices', 'ch')
            ->where('c.id = :idChoice')
            ->setParameter('idChoice', $choice->getId());

        return $qb->getQuery()->getResult();
    }
}
