<?php

namespace PM\SurveythorBundle\Repository;

/**
 * QuestionConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionConditionRepository extends BaseRepository
{
}
