<?php

namespace PM\SurveythorBundle\Repository;

/**
 * MultipleChoiceAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultipleChoiceAnswerRepository extends BaseRepository
{
}
