<?php

namespace PM\SurveythorBundle\Repository;

/**
 * QuestionTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTemplateRepository extends BaseRepository
{
}
