<?php

namespace PM\SurveythorBundle\Repository;

/**
 * QuestionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionGroupRepository extends BaseRepository
{
}
