<?php

namespace PM\SurveythorBundle\Repository;

/**
 * ResultItemTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultItemTemplateRepository extends BaseRepository
{
}
