<?php

namespace PM\SurveythorBundle\Repository;

/**
 * ResultItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultItemRepository extends BaseRepository
{
}
