<?php

namespace PM\SurveythorBundle\Repository;

/**
 * ResultAnswerSingleChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultAnswerSingleChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
