<?php

namespace PM\SurveythorBundle\Repository;

/**
 * ResultAnswerTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultAnswerTextRepository extends \Doctrine\ORM\EntityRepository
{
}
