<?php

namespace PM\SurveythorBundle\Repository;

/**
 * ResultAnswerMultipleChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultAnswerMultipleChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
