<?php

namespace PM\SurveythorBundle\Repository;

/**
 * ResultRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
