<?php

namespace PM\SurveythorBundle\Repository;

/**
 * ResultAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
