<?php

namespace PM\SurveythorBundle\Repository;

/**
 * SingleChoiceAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SingleChoiceAnswerRepository extends BaseRepository
{
}
