<?php

namespace PM\SurveythorBundle\Repository;

/**
 * SurveyTextItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyTextItemRepository extends \Doctrine\ORM\EntityRepository
{
}
