<?php

namespace PM\SurveythorBundle\Repository;

/**
 * SurveyItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyItemRepository extends \Doctrine\ORM\EntityRepository
{
}
