<?php

namespace PM\SurveythorBundle\Repository;

/**
 * TextItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextItemRepository extends \Doctrine\ORM\EntityRepository
{
}
