<?php

namespace PM\SurveythorBundle\Repository;

/**
 * TextAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextAnswerRepository extends BaseRepository
{
}
