services:
    _defaults:
        autowire: true

    survey_controller:
        class: PM\SurveythorBundle\Controller\SurveyController

    result_controller:
        class: PM\SurveythorBundle\Controller\ResultController

    survey_item_controller:
        class: PM\SurveythorBundle\Controller\SurveyItemController

    choice_controller:
        class: PM\SurveythorBundle\Controller\ChoiceController
