imports:
    - { resource: services_controller.yml }
    - { resource: services_repository.yml }
    - { resource: services_event.yml }

services:
    app.menu_builder:
        class: PM\SurveythorBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.authorization_checker"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

