services:
    app.repository.survey_repository:
        class: PM\SurveythorBundle\Repository\SurveyRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - PM\SurveythorBundle\Entity\Survey

    app.repository.survey_item_repository:
        class: PM\SurveythorBundle\Repository\SurveyItemRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - PM\SurveythorBundle\Entity\SurveyItem

    app.repository.result_repository:
        class: PM\SurveythorBundle\Repository\ResultRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - PM\SurveythorBundle\Entity\Result

    app.repository.condition_repository:
        class: PM\SurveythorBundle\Repository\ConditionRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - PM\SurveythorBundle\Entity\Condition

    app.repository.choice_repository:
        class: PM\SurveythorBundle\Repository\ChoiceRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - PM\SurveythorBundle\Entity\Choice
