imports:
    - { resource: services/services-controller.yml }
    - { resource: services/services-repository.yml }
    - { resource: services/services-event.yml }

services:
    app.menu_builder:
        class: PM\SurveythorBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

