PM\SurveythorBundle\Entity\ResultItem:
    properties:
        singleChoiceAnswer:
            - Valid: ~
        multipleChoiceAnswer:
            - Valid: ~
        childItems:
            - Valid: ~
