services:
    _defaults:
        autowire: true

    AppBundle\Repository\AllowedOriginRepository: ~

    PM\SurveythorBundle\Repository\ChoiceRepository: ~

    PM\SurveythorBundle\Repository\ConditionRepository: ~

    PM\SurveythorBundle\Repository\ResultRepository: ~

    PM\SurveythorBundle\Repository\SurveyItemRepository: ~

    PM\SurveythorBundle\Repository\SurveyRepository: ~
