services:
    AppBundle\Repository\AllowedOriginRepository:
        class: AppBundle\Repository\AllowedOriginRepository
        factory: [ '@doctrine', getRepository ]
        arguments:
            - AppBundle:AllowedOrigin
