
AppBundle\Entity\ResultItems\SingleChoiceAnswer:
    properties:
        choice:
#            - Choice:
#                callback: 'getChoices'
#                message: 'validation.single_choice_answer.choice'
            - NotBlank:
                message: 'single_choice_answer.not_blank'
AppBundle\Entity\ResultItems\MultipleChoiceAnswer:
    properties:
        choices:
            - Count:
                min: 1
                minMessage: 'multiple_choice_answer.min_count'
#            - Collection:
#                fields:
#                    choices: ~
#                        - Choice:
#                        - NotNull:
#                            message: 'multiple_choice_answer.not_blank'
#                            multiple: true
#                            callback: getChoices.getChoice
#                            message: 'multiple_choice_answer.not_blank2'
#                            min: 1
#                            minMessage: 'multiple_choice_answer.not_blank1'
#                            max: 5
#                            maxMessage: 'multiple_choice_answer.not_blank5'
#                            strict: true
#                message: 'multiple_choice_answer.not_blank1'
#            - NotNull:
#                message: 'multiple_choice_answer.not_blank'
#            - NotBlank:
#                message: 'multiple_choice_answer.not_blank'
AppBundle\Entity\ResultItems\TextAnswer:
    properties:
        value:
            - NotBlank:
                message: 'text_answer.not_blank'
AppBundle\Entity\ResultItem:
    properties:
        singleChoiceAnswer:
            - Valid: ~
        multipleChoiceAnswer:
            - Valid: ~
        textAnswer:
            - Valid: ~
        childItems:
            - Valid: ~
AppBundle\Entity\Survey:
    properties:
        title:
            - NotBlank: ~
#    constraints:
#        - Callback: validate
AppBundle\Entity\BunnyUser:
    properties:
        firstName:
            - NotBlank:
                message: 'first_name.not_blank'
        lastName:
            - NotBlank:
                message: 'last_name.not_blank'
        email:
            - NotBlank:
                message: 'email.not_blank'
            - Email:
                message: 'email.email'
        telephoneNumber:
            - NotBlank:
                message: 'telephone_number.not_blank'
        companyTitle:
            - NotBlank:
                message: 'company_title.not_blank'
        street:
            - NotBlank:
                message: 'street.not_blank'
        streetNumber:
            - NotBlank:
                message: 'street_number.not_blank'
        city:
            - NotBlank:
                message: 'city.not_blank'
        zipCode:
            - NotBlank:
                message: 'zip_code.not_blank'
        isDataProcessingConfirmed:
            - IsTrue:
                message: 'is_data_processing_confirmed.not_blank'
            - NotBlank:
                message: 'is_data_processing_confirmed.not_blank'

AppBundle\Entity\AllowedOrigin:
    properties:
        originName:
            - Url: ~
            - NotBlank: ~
        title:
            - NotBlank: ~
