AppBundle\Entity\Choice:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
            nullable: true
        value:
            type: integer
            nullable: true
        sortOrder:
            type: integer
            nullable: true

    manyToOne:
        question:
            targetEntity: AppBundle\Entity\SurveyItems\Question
            inversedBy: choices

    lifecycleCallbacks:
        prePersist: [ setInitialSortOrder ]
