AppBundle\Entity\QuestionTemplate:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        formType:
            type: string
            length: 255
            nullable: true
        result:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
