PM\SurveythorBundle\Entity\AnswerGroup:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\AnswerGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        result:
            targetEntity: PM\SurveythorBundle\Entity\Result
            inversedBy: answerGroups

    lifecycleCallbacks: {  }
