PM\SurveythorBundle\Entity\Answer:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\AnswerRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        mc: MultipleChoiceAnswer
        text: TextAnswer
        sc: SingleChoiceAnswer

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
            nullable: true

    manyToOne:
        result:
            targetEntity: PM\SurveythorBundle\Entity\Result
            inversedBy: answers

        question:
            targetEntity: PM\SurveythorBundle\Entity\Question

        parentAnswer:
            targetEntity: PM\SurveythorBundle\Entity\Answer
            inversedBy: childAnswers

    oneToMany:
        childAnswers:
            targetEntity: PM\SurveythorBundle\Entity\Answer
            mappedBy: parentAnswer
            cascade:
                - persist

    lifecycleCallbacks: {}
