PM\SurveythorBundle\Entity\Answer:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\AnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        value:
            type: integer
        event:
            type: string
            length: 255
            nullable: true

    manyToOne:
        question:
            targetEntity: PM\SurveythorBundle\Entity\Question
            inversedBy: answers


    oneToMany:
        childQuestions:
            targetEntity: PM\SurveythorBundle\Entity\Question
            mappedBy: parentAnswer
            cascade:
                - persist
            joinTable:
                name: childanswer_parentquestion


    lifecycleCallbacks: {  }
