PM\SurveythorBundle\Entity\ResultItemTemplate:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\ResultItemTemplateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        formType:
            type: string
            length: 255
    lifecycleCallbacks: {  }
