PM\SurveythorBundle\Entity\ResultAnswer:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\ResultAnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: text

    manyToOne:
        result:
            targetEntity: PM\SurveythorBundle\Entity\Result
            inversedBy: resultAnswers

        answer:
            targetEntity: PM\SurveythorBundle\Entity\Answer

    lifecycleCallbacks: {  }
