PM\SurveythorBundle\Entity\ResultItems\MultipleChoiceAnswer:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\MultipleChoiceAnswerRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToOne:
        resultItem:
            targetEntity: PM\SurveythorBundle\Entity\ResultItem
            inversedBy: multipleChoiceAnswer
            cascade:
                - merge
                - detach

    manyToOne:
        question:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItems\Question
            cascade:
                - merge
                - detach

    manyToMany:
        choices:
            targetEntity: PM\SurveythorBundle\Entity\Choice
            cascade:
                - merge
                - detach

    lifecycleCallbacks: {  }
