PM\SurveythorBundle\Entity\ResultAnswer:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\ResultAnswerRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        mc: ResultAnswerMultipleChoice
        text: ResultAnswerText
        sc: ResultAnswerSingleChoice

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
            nullable: true

    manyToOne:
        result:
            targetEntity: PM\SurveythorBundle\Entity\Result
            inversedBy: resultAnswers

        question:
            targetEntity: PM\SurveythorBundle\Entity\Question

        parentAnswer:
            targetEntity: PM\SurveythorBundle\Entity\ResultAnswer
            inversedBy: childAnswers

    oneToMany:
        childAnswers:
            targetEntity: PM\SurveythorBundle\Entity\ResultAnswer
            mappedBy: parentAnswer
            cascade:
                - persist

    lifecycleCallbacks: {}
