PM\SurveythorBundle\Entity\ResultItems\MultipleChoiceAnswer:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToOne:
        resultItem:
            targetEntity: PM\SurveythorBundle\Entity\ResultItem
            inversedBy: multipleChoiceAnswer

    manyToOne:
        question:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItems\Question

    manyToMany:
        choices:
            targetEntity: PM\SurveythorBundle\Entity\Choice
            cascade:
                - persist

    lifecycleCallbacks: {  }
