PM\SurveythorBundle\Entity\ResultAnswer:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\ResultAnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: text

    manyToOne:
        result:
            targetEntity: PM\SurveythorBundle\Entity\Result
            inversedBy: resultAnswers

        question:
            targetEntity: PM\SurveythorBundle\Entity\Question

        answer:
            targetEntity: PM\SurveythorBundle\Entity\Answer

        parentAnswer:
            targetEntity: PM\SurveythorBundle\Entity\ResultAnswer

    oneToMany:
        childAnswers:
            targetEntity: PM\SurveythorBundle\Entity\ResultAnswer
            mappedBy: childAnswers


    lifecycleCallbacks: {  }
