PM\SurveythorBundle\Entity\ResultItems\ResultTextItem:
    type: entity
    table: result_text_item
    repositoryClass: PM\SurveythorBundle\Repository\ResultItems\ResultTextItemRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToOne:
        resultItem:
            targetEntity: PM\SurveythorBundle\Entity\ResultItem
            inversedBy: resultTextItem

    fields:
        text:
            type: text

    lifecycleCallbacks: {  }
