PM\SurveythorBundle\Entity\SurveyItems\ItemGroup:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\SurveyItems\ItemGroupRepository

    oneToMany:
        surveyItems:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItem
            mappedBy: itemGroup
            cascade:
                - persist
                - remove
            orderBy: { 'sortOrder' : 'ASC'}

    lifecycleCallbacks: {  }
