PM\SurveythorBundle\Entity\SurveyItems\TextItem:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\TextItemRepository

    fields:
        text:
            type: text

    lifecycleCallbacks: {  }
