PM\SurveythorBundle\Entity\SurveyItem:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\SurveyItemRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        question: PM\SurveythorBundle\Entity\SurveyItems\Question
        textItem: PM\SurveythorBundle\Entity\SurveyItems\TextItem
        itemGroup: PM\SurveythorBundle\Entity\SurveyItems\ItemGroup

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        sortOrder:
            type: integer
        title:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        displayTitle:
            type: boolean

    manyToOne:
        survey:
            targetEntity: PM\SurveythorBundle\Entity\Survey
            inversedBy: surveyItems
        template:
            targetEntity: PM\SurveythorBundle\Entity\ResultItemTemplate
        itemGroup:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItems\ItemGroup
            inversedBy: surveyItems

    oneToMany:
        conditions:
            targetEntity: PM\SurveythorBundle\Entity\Condition
            mappedBy: surveyItem

    lifecycleCallbacks: {  }
