PM\SurveythorBundle\Entity\SurveyItem:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\SurveyItemRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        sortOrder:
            type: integer
        title:
            type: text
        displayTitle:
            type: boolean

    manyToOne:
        survey:
            targetEntity: PM\SurveythorBundle\Entity\Survey
            inversedBy: surveyItems
        parentItem:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItem
            inversedBy: childItems
        template:
            targetEntity: PM\SurveythorBundle\Entity\ResultItemTemplate

    oneToOne:
        question:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItems\Question
            inversedBy: surveyItem
        textItem:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItems\TextItem
            inversedBy: surveyItem

    oneToMany:
        conditions:
            targetEntity: PM\SurveythorBundle\Entity\Condition
            mappedBy: surveyItem
        childItems:
            targetEntity: PM\SurveythorBundle\Entity\SurveyItem
            mappedBy: parentItem

    lifecycleCallbacks: {  }
