PM\SurveythorBundle\Entity\TextAnswer:
    type: entity
    table: null
    repositoryClass: PM\SurveythorBundle\Repository\TextAnswerRepository

    fields:
        value:
            type: text

    lifecycleCallbacks: {  }
